#+TITLE: We are making some changes!
#+DATE: 2023-09-03T11:40:20-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: announcements site
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: As you have no doubt noticed, the site is different than it was before. We are moving this site to more of a blog-style format.

As you have no doubt noticed, the site is different than it was before. We are moving this site to more of a blog-style format. This is being done for a few reasons:
1. We no longer have the time to work on large projects and many of those of languished without recent updates
2. We believe the root domain, [[http://onigirionegai.info][onigirionegai.info]] should focus on information on the organization
3. We each have our own websites now as well and would like those to be more discoverable
4. If we do work on other large projects, we would like them to have separate websites with their own style and theme rather than just be part of a larger "root" site
Let me explain each of these in a bit more detail.

* We no longer have the time...
Sadly we have all become much busier as our lives have moved on and we are not able to provide the time and attention we once dreamt of when we came together. Rather than deciding to close the site, however, I decided to leave it open. It will now serve as a launchpad of discovery. I will blog about my own small projects and about the state of my collaborator's projects. They may be smaller, but we are not just sitting on our hands. We simply need to be able to live and the types of large projects that cannot provide income at the moment are not things we can focus too much time on. We hope, that, in the future, we will be able to come together again. I talk a little about this on the [[{{% ref "about.org" %}}][about page]] and will elaborate further a little later. Please have patience with us and don't forget to check out our other sites!
* The domain is .info, should it should be information-focused, right?
I won't say too much here, but this was a factor. The previous site was a little too unfocused and general. I think, being that this is a .info domain, at least the root site should be more information-focused. Now I won't go so far as to tell my collaborators how they should run their sites, or the type of content they should have even if their URL is still attached to this one. I just think /this/ site should be more focused on providing information, organization news, site news, and announcements, than on the projects themselves. This also leads into the last point, but first!
* We each have our own websites and would like those to be more discoverable
One look at the home page and you'll find a pinned post, this is the aforementioned [[{{% ref "about.org" %}}][about page]]. That page lists the sites that each of us now work on. Within a couple of clicks we now have a list of sub-sites. These were not even mentioned previously. It was up to each member to promote their personal sites even if they were hosted here. This is now no longer the case. So be sure to check them out! Now onto that last point that I mentioned just one paragraph ago.
* We want websites for each project not one "one-size-fits-none" site
While the original idea of this site as a means of both introducing ourselves and our projects was not a bad one, it wasn't the best. One over-arching site is just too big and any future projects we do come together for would simply be lost in a sea of other projects, especially if those projects are many and all large. Therefore, each project will have its own dedicated site that will be designed for its own identity. This, of course is something that will happen later. I mentioned we would /like/ to work on larger projects, but that is not possible at this time. If you would like to help though, I have information on how that could be possible on the [[{{% ref "about.org" %}}][most link page ever]]!
