#+TITLE: Forums moving to GitHub Discussions
#+DATE: 2023-11-16T12:26:36-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: site news
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Over the past couple of years I have hosted a set of discussion forums on this server using phpBB. The idea was to give members of our community a way to discuss things with us and each other and generally just get together. Forums were also going to be away for patrons to access and discuss content and the direction of stories. We have had no adoption and it became a place where I could exchange ideas and private messages only with the other staff members and friends. While this is not a bad purpose, as this really doesn't affect the server that much we have decided to shut these forums down. If anyone would like to discuss this site or our future plans, they can still do so, but will now require a GitHub account as we have simply set up GitHub Discussions for each repository associated with the server. The one for this site, for example, is located [[https://github.com/jjon-saxton/onigiri/discussions][here]].

* Comments vs Discussions vs Issues
While currently not enabled (I'm weighing options) on this site, we are looking to enable comments on each blog page to allow for some engagement. This is currently done on [[https://onigirionegai.info/~yayoi/][Yayoi's site]] using a GitHub project called utteranc.es. This allows people to post comments as issues in GitHub. The comments still appear on the page below the main content as they should for a blog, but she gets to review, reply, and manage them from her repo. While this seems awesome, it does require that everyone has a GitHub account, so I'm weighing other options for engagement. If we do establish comments those would be used for specific information on a page while discussions would be more for project discussion and general site comments. You can also raise issues on the GitHub repo if you notice problems. Yayoi uses her comment section for that as well because, as I mentioned, they use GitHub issues in the backend, but that may not be the best if we use something else.

* Future of Community Engagement
I would still like to build a community here. Once I have a comment system in place I'm hoping everyone will use it. We are artists and we like showing our art. Its great to just create things, but would be so much better if we knew it was really appriciated. At the end of the day that's what this is all about. Please engage with us on our GitHub discussions or even in the comment sections if/when they are available. Thank you.

** List of Discussions
+ [[https://github.com/jjon-saxton/onigiri/discussions][Onigiri☆Onegai]]
+ [[https://github.com/yayoi-chi/yaya-world/discussions][Yaya's World]] (Don't forget to hit up Yayoi in her comments too 😉)
