#+TITLE: Living With/in Garuda
#+DATE: 2024-05-10T19:53:58-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: blog
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

My main computer is actually a Manjaro Linux with Hyprland install. I like Hyprland, its a really good Wayland compositor. The problem is the main computer actually has an Nvidia graphics card and the drivers and/or Wayland itself just isn't ready for Nvidia. I'll go into the full set up later, but, I have a way around this and that's a Garuda Linux VM.

* Playing with Virtual Machines
I've always had some odd perverse pleasure in running machines within machines. I've been trying to do that for many years, starting with trying to run Windows 3.11 for Workgroups in a Windows 7 machine. I kept this up for sometime, sometimes emulating totally different architectures and sometimes just virtualizing other operating systems and environments. Recently it was Windows 10 on Linux using QEMU/KVM and a GPU passthrough. I rarely use that machine, but I do sometimes need it to benchmark games and compare them to running on Linux, it was for this reason that I thought of playing with a Linux VM also passing through the Nvidia card. This way I don't have to use something like single GPU passthrough to keep using the Windows 10 VM. Technically the machine does have /two/ graphics cards.

* Giving the Host and Hyprland Intel Graphics
The machine has integrated Intel HD Graphics. While only suited for the lightest of gaming, it does work very well for running a modern compositor. The machine is used mostly for coding and school work so it works well for that and Wayland has no problem with the intel drivers.

* Gaming in Garuda
I set Garuda Linux up by cloning the Windows VM, swapping the disk image for a physical drive and then installing Garuda through the live environment. This got me a bunch of things I didn't need to run games, at least not the kinds I wanted to run, but they weren't hard to remove. I set up the VM to auto login and boot up Steam in Big Picture mode so it could be ready to launch a game right away.

So far, even though this a VM, it works very well with Garuda. This is likely because cloning the Windows machine meant that I also cloned the GPU passthrough set up so Garuda gets a full Graphics card. I heard that distros like Garuda would normally not run well in a VM.

* Living +With+ in Garuda
I've taken to do a bit more in the KDE desktop environment in Garuda. Usually I start the Garuda VM up and just leave it up on the weekend so if I do any web browsing or other work its inside Garuda. I haven't customized the theme yet, I like everything about the default them and would probably only change the wallpaper...eventually.

Anyway, that's what I have to say about living in Garuda. So far it is a solid gaming, coding, and browsing experience. If I /do/ customize the the theme, I'll be sure to share screenshots!
