#+TITLE: "Macs Can't Game"
#+DATE: 2023-09-27T18:40:52-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: news blog
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

If you're a user of a modern Mac, not a Macintosh or Apple computer, but a Mac, because that's what we call them these days, then you have probably heard /someone/ say, but Jon (I'm using my name because I have heard this, but use your name instead) Macs can't game, right? I mean its kind of the reputation the platform has especially today since, due to the fundamentally different architecture, we can't just throw a copy of Windows on there and call it a day. The question is: Is this really true? To really answer this question we have to actually understand the statement. Let's start there.

* What do you mean "Macs Can't Game"?
This is really an over generalized statement and we first need to understand this before we can support or refute it. Here is what I mean. The statement assumes, like many things in life these days, a digital state. That is like newer digital TV signals you either have 100% or 0%. There are no states in between. Applying this to Mac gaming means that you either can play 100% of the games you own or you can't play any games at all. However, this negates some of the actual accomplishments of the system and makes it sound as if you can't play any games on a Mac. This is not true, and I don't just mean Apple Arcade games, but lets talk about that.

* Apple Arcade
The above statement assumes no games run on Macs. It even negates Apple Arcade. Now, I will give many PC gamers a pass here. The type of games available on Apple Arcade are probably not the games they actually want to play. Because of the nature of Apple Arcade and requirements from Apple, all games released on Apple Arcade must support all platform that run the arcade software, this includes devices like the Apple TV and iPhone SE. Many Apple Arcade games, therefore, are phone games or very low quality games that you could just play on your phone, so what's the point in playing them on a Mac and why even include them? Well, you see, they are still games and that means that Macs do have a large library of games they can play. As I said though, I'll give you PC gamers a bit of a pass, but we should probably change the statement to reflect this "Macs can't play the games I want to play."

* AAA Titles
Only that also isn't entirely accurate. I /could/ bust out my nerd game and say something to the effect of: Well, Intel Macs exist still an you could just use boot camp on one of those computers to install Windows and therefore there are a lot of Macs that can play whatever game you want, I don't even need to go there. The very fact that Steam runs on Macs /should/ allude to the fact that there are decent, non-Apple Arcade games, that actually run natively on even Apple Silicon M1/M2 Macs. Just one title that I noticed is "No Man's Sky". You can install and run that through Steam on macOS without issues. Is it the best experience out there? Probably not, certainly not on something like the 2020 M1 MacBook Air, but even that is just about as good as a Steam Deck. "No Man's Sky" is also no the only game that runs on a Mac. Just a quick look at my own library shows the following AAA titles that I could install and run on a Mac:
1. BioShock/BioShock 2
2. Deues Ex: Mankind Divided
3. Middle Earth: Shadow of Mordor
4. Rise of the Tomb Raider
5. Shadow of the Tomb Raider
6. Tomb Raider
7. No Man's Sky
Is that a really long list? No, not by a long shot, but seven games is more than none. Are these games all that new? Also no, but then again I don't have very many new titles in my own library to look at. The point is that there /are/ games that you can play on a Mac so saying Macs can't game is not exactly accurate.

* Does the really matter?
The harsh reality is of the 202 titles in my library (that's all titles), only 30 will run on the Mac. Also, I don't play many of the 30 games that would run. "No Man's Sky" is the only game I have played extensively on the Mac, but that does mean I have played a game on the Mac and, in fact, I have also played non-steam games including "The Sims 4", "StarCraft II", and "Fantasian" (one of which is a very good Apple Arcade title). So I'm not only capable of playing games on the Mac, but I have actually done so. Is it my platform of choice for gaming? No. I wouldn't even use it for productivity. I know at least one person who would use a Mac over a PC (even running Linux), but not for running games. That being said, the statement isn't about preference it is about capability. Macs are capable of running games therefore to say they can't is just wrong. However, what can it hurt to just say they can't play games? After all they certainly don't play many so its not entirely incorrect and maybe it will better prepare people for when they are trying to decide on that one laptop for school or work. Well, there are actually problems with a blanket label like that:
1. It breads an attitude in consumers that they should not buy a Mac if gaming is something they want to use it for at all
2. It makes the Mac look like a platform that should not be targeted as platform to release games on
This could effect efforts of those who are considering releasing games for the Mac and result in a sort of chicken and egg problem. There are no games for the Mac, so no one buy a Mac for gaming, therefore there is no interest in developing games for the Mac, therefore the are no games for the Mac. If we at least acknowledge the Mac's potential as a platform for games then perhaps we can break that cycle. Unfortunately, that is up to us.

* What next?
In my next blog post I will be comparing the Mac and the Steam Deck as gaming platforms. Both of these devices are not typically targeted as release platforms for large PC games, but one plays many more games then the other. I'll discuss why and why it matters. I'll also bring up the GamePorting ToolKit from Apple and how it is different from Valve's efforts. I'll even explain why it likely won't help the Mac. Stay tuned!
