#+TITLE: Site Look
#+DATE: 2023-09-14T12:47:20-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: news site
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: It has been a couple of weeks now since I have changed the purpose of this site. With this change came a new look. To be honest the look was chosen for two reasons and neither are particularly good; a) It looked pretty good, and b) it seemed easy to install

It has been a couple of weeks now since I have changed the purpose of this site. With this change came a new look. To be honest the look was chosen for two reasons and neither are particularly good:
1. It looked pretty good
2. It seemed pretty easy to install

If I'm being even more honest I would say the second reason is the biggest factor. Which is related to how, unfortunately, lazy I've come when it comes to this site. I fully recognize that the original site had a lot more...we'll call it...personality. To me it just had a look to it that screamed anime or visual novel without looking too much like a Japanese site. It struck a good balance between the type of content we provided and the origin of our group, that being the United States. This site does look fairly professional, but it lacks some of the charm of the old one. I understand this. The problem is, is there a problem? What I mean is, is it bad that we lost that charm? Maybe its better without it? That's where I need your opinion. I have a [[https://forums.onigirionegai.info/viewtopic.php?t=28][forum post]] up with a poll and would like anyone to tell me what they think. Should we try to get that personality back, or is this better?

While I would love to tell you that I have more news, it has been a bit slow on that front today. I am looking at other sites and pages to showcase though. I've been catching up on anime and trying to help some friends, so I haven't had as much time to go through some of the suggestions. I'll have something up for next week though. Right now, let's enjoy the break :smile:
